# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openmorph < Formula
  desc "A tool for transforming and optimizing OpenAPI specifications"
  homepage "https://github.com/developerkunal/OpenMorph"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/developerkunal/OpenMorph/releases/download/v0.1.0/openmorph_0.1.0_darwin_amd64.tar.gz"
      sha256 "ebf3163188e63edd105316a91babde37374c4b01055b89eb6d14982420f51694"

      def install
        bin.install "openmorph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/developerkunal/OpenMorph/releases/download/v0.1.0/openmorph_0.1.0_darwin_arm64.tar.gz"
      sha256 "bb7da08754b43fa54a9a0eeabed29febd0a8f5bce84976f466e34a4db525a9e4"

      def install
        bin.install "openmorph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/developerkunal/OpenMorph/releases/download/v0.1.0/openmorph_0.1.0_linux_amd64.tar.gz"
      sha256 "55ed35eb961f849b397936428c637d8ae4b73242f6f4bfd88b238d5e8ffa383b"
      def install
        bin.install "openmorph"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/developerkunal/OpenMorph/releases/download/v0.1.0/openmorph_0.1.0_linux_arm64.tar.gz"
      sha256 "2a7635ef075db7dce77aefec17168fe348ed7fa3b3ea92e176cd773ec455c683"
      def install
        bin.install "openmorph"
      end
    end
  end

  test do
    system "#{bin}/openmorph --version"
  end
end
