# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Openmorph < Formula
  desc "A tool for transforming and optimizing OpenAPI specifications"
  homepage "https://github.com/developerkunal/OpenMorph"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/developerkunal/OpenMorph/releases/download/v0.2.0/openmorph_0.2.0_darwin_amd64.tar.gz"
      sha256 "65de6f0ebf8244a51c2abcabe73912b745d842bb42b56b8fff20caf95520c6db"

      def install
        bin.install "openmorph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/developerkunal/OpenMorph/releases/download/v0.2.0/openmorph_0.2.0_darwin_arm64.tar.gz"
      sha256 "7f1cde3dc7e112df24950a0e2236df8609f79245ed040ba237cfcb3dc8a0828c"

      def install
        bin.install "openmorph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/developerkunal/OpenMorph/releases/download/v0.2.0/openmorph_0.2.0_linux_amd64.tar.gz"
      sha256 "a75b83eb64c8dc121a8088d3fb1d25b552b487ec4416071302e46ec6d9bfdad9"
      def install
        bin.install "openmorph"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/developerkunal/OpenMorph/releases/download/v0.2.0/openmorph_0.2.0_linux_arm64.tar.gz"
      sha256 "085d9323de707c66c16e490cdaa3f20f6267f3992679eec07c2e13f98d382a98"
      def install
        bin.install "openmorph"
      end
    end
  end

  test do
    system "#{bin}/openmorph --version"
  end
end
